name: 'Setup Environment Variables'
description: 'Exports set list of environment variables to GITHUB_ENV with sensible defaults.'

inputs:
  GCP_PROJECT_ID:
    description: 'ProjectID of the GCP project to deploy to.'
    required: true
  REGISTRY_HOSTNAME:
    description: 'Hostname of Container Registry'
    default: 'gcr.io'
    required: false
  TLD:
    description: 'Top Level Domain to create subdomain on.'
    required: true
  NAMESPACE: 
    description: 'Allows to override the desired NAMESPACE variable'
    required: false
    default: ${{ github.ref_name }}
  SERVICE_NAME: 
    description: 'Allows to override the desired SERVICE_NAME variable'
    required: false
    default: ${{ github.repository }}

runs:
  using: 'composite'
  steps:
    - name: SHORT_SHA
      run: |
        SHORT_SHA=${GITHUB_SHA:0:7}
        echo "SHORT_SHA=$SHORT_SHA"
        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
      shell: bash

    - name: NAMESPACE
      run: |
        NAMESPACE=$(${{ github.action_path }}/clean_variable.sh ${{ inputs.NAMESPACE }})
        echo "NAMESPACE=$NAMESPACE"

        echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
      shell: bash

    - name: SERVICE_NAME
      run: |
        SERVICE_NAME=$(${{ github.action_path }}/clean_variable.sh ${{ inputs.SERVICE_NAME }})
        
        echo "SERVICE_NAME=$SERVICE_NAME"
        echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
      shell: bash

    - name: BUILD_IMAGE
      run: |
        BUILD_IMAGE=${{ inputs.REGISTRY_HOSTNAME }}/${{ inputs.GCP_PROJECT_ID }}/$SERVICE_NAME:$SHORT_SHA
        echo "BUILD_IMAGE=$BUILD_IMAGE"
        echo "BUILD_IMAGE=$BUILD_IMAGE" >> $GITHUB_ENV
      shell: bash

    - name: HOSTNAME
      run: |
        HOSTNAME=$NAMESPACE.${{ inputs.TLD }}
        echo "HOSTNAME=$HOSTNAME"
        echo "HOSTNAME=$HOSTNAME" >> $GITHUB_ENV
      shell: bash

    - name: CERT_NAME
      run: |
        TLD=${{ inputs.TLD }}
        CERT_NAME=wildcard-${TLD//./-}
        echo "CERT_NAME=$CERT_NAME"
        echo "CERT_NAME=$CERT_NAME" >> $GITHUB_ENV
      shell: bash