name: 'Setup Environment Variables'
description: 'Exports set list of environment variables to GITHUB_ENV with sensible defaults.'

inputs:
  GCP_PROJECT_ID:
    description: 'ProjectID of the GCP project to deploy to.'
    required: true
  REGISTRY_HOSTNAME:
    description: 'Hostname of Container Registry'
    default: 'gcr.io'
    required: false
  TLD:
    description: 'Top Level Domain to create subdomain on.'
    required: true
  NAMESPACE:
    description: 'Allows to override the desired NAMESPACE variable'
    required: false
  SERVICE_NAME:
    description: 'Allows to override the desired SERVICE_NAME variable'
    required: false
    default: ${{ github.repository }}

outputs:
  short_sha:
    description: 'Short Sha'
    value: ${{ steps.SHORT_SHA.outputs.SHORT_SHA }}
  env:
    description: 'Kubernetes Environment'
    value: ${{ steps.ENV.outputs.ENV }}
  namespace:
    description: 'Kubernetes Namespace'
    value: ${{ steps.NAMESPACE.outputs.NAMESPACE }}
  service_name:
    description: 'Kubernetes Service Name'
    value: ${{ steps.SERVICE_NAME.outputs.SERVICE_NAME }}
  build_image:
    description: 'Docker Build Image'
    value: ${{ steps.BUILD_IMAGE.outputs.BUILD_IMAGE }}
  hostname:
    description: 'Hostname'
    value: ${{ steps.HOSTNAME.outputs.HOSTNAME }}
  cert_name:
    description: 'TLS Certificate Name'
    value: ${{ steps.CERT_NAME.outputs.CERT_NAME }}

runs:
  using: 'composite'
  steps:
    - name: SHORT_SHA
      id: SHORT_SHA
      run: |
        SHORT_SHA=${GITHUB_SHA:0:7}
        echo "SHORT_SHA=$SHORT_SHA"
        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

        echo "::set-output name=SHORT_SHA::$SHORT_SHA"
      shell: bash

    - name: Get Ref
      id: get_ref
      uses: dmsi-io/gha-get-ref@v1
      with:
        custom_ref: ${{ inputs.NAMESPACE }}
    
    - name: ENV
      id: ENV
      run: |
        ENV=${{ github.ref_type == 'tag' &&  'production' || 'development'}}
        echo "ENV=$ENV"
        echo "ENV=$ENV" >> $GITHUB_ENV

        echo "::set-output name=ENV::$ENV"
      shell: bash

    - name: NAMESPACE
      id: NAMESPACE
      run: |
        NAMESPACE=$(${{ github.action_path }}/clean_variable.sh ${{ steps.get_ref.outputs.ref_name }})

        echo "NAMESPACE=$NAMESPACE"
        echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV

        echo "::set-output name=NAMESPACE::$NAMESPACE"
      shell: bash

    - name: SERVICE_NAME
      id: SERVICE_NAME
      run: |
        SERVICE_NAME=$(${{ github.action_path }}/clean_variable.sh ${{ inputs.SERVICE_NAME }})

        echo "SERVICE_NAME=$SERVICE_NAME"
        echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV

        echo "::set-output name=SERVICE_NAME::$SERVICE_NAME"
      shell: bash

    - name: Docker Tag
      id: docker_tag
      run: |
        SEMVER_REGEX="^(v*0|v*[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$"
        RELEASE_REGEX="release/*"
        REF="${{ steps.get_ref.outputs.ref_name }}"

        if [ "${{ github.ref_type }}" = "tag" ]; then
          echo "::set-output name=tag_name::$REF"

        elif [[ "$REF" =~ $RELEASE_REGEX ]] && [[ "${REF##*/}" =~ $SEMVER_REGEX ]]; then
          echo "::set-output name=tag_name::${REF##*/}"

        else
          echo "::set-output name=tag_name::$SHORT_SHA"

        fi
      shell: bash

    - name: BUILD_IMAGE
      id: BUILD_IMAGE
      run: |
        BUILD_IMAGE=${{ inputs.REGISTRY_HOSTNAME }}/${{ inputs.GCP_PROJECT_ID }}/$SERVICE_NAME:${{ steps.docker_tag.outputs.tag_name }}

        echo "BUILD_IMAGE=$BUILD_IMAGE"
        echo "BUILD_IMAGE=$BUILD_IMAGE" >> $GITHUB_ENV

        echo "::set-output name=BUILD_IMAGE::$BUILD_IMAGE"
      shell: bash

    - name: HOSTNAME
      id: HOSTNAME
      run: |
        HOSTNAME=$NAMESPACE.${{ inputs.TLD }}
        echo "HOSTNAME=$HOSTNAME"
        echo "HOSTNAME=$HOSTNAME" >> $GITHUB_ENV

        echo "::set-output name=HOSTNAME::$HOSTNAME"
      shell: bash

    - name: CERT_NAME
      id: CERT_NAME
      run: |
        TLD=${{ inputs.TLD }}
        CERT_NAME=wildcard-${TLD//./-}
        echo "CERT_NAME=$CERT_NAME"
        echo "CERT_NAME=$CERT_NAME" >> $GITHUB_ENV

        echo "::set-output name=CERT_NAME::$CERT_NAME"
      shell: bash
