name: Test gha-env-variables

on:
  - push

jobs:
  test-gha-env-variables:
    runs-on: ubuntu-latest
    name: Test gha-env-variables
    steps:
      - name: Export Environment Variables
        uses: dmsi-io/gha-env-variables@main
        with:
          TLD: agility.dmsi.io
          GCP_PROJECT_ID: test-project-id

      - name: Install envsubst
        run: |
          env | sort
          sudo apt-get install gettext
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Environment Variable Replacement
        run: cat example.txt | envsubst

  test-gha-env-variables-defaults:
    runs-on: ubuntu-latest
    name: Test gha-env-variables (override defaults)
    steps:
      - name: Export Environment Variables (override defaults)
        uses: dmsi-io/gha-env-variables@main
        with:
          TLD: agility.dmsi.io
          GCP_PROJECT_ID: test-project-id
          NAMESPACE: something/testing-OVERRIDE
          SERVICE_NAME: something/testing-override

      - name: Install envsubst
        run: |
          env | sort
          sudo apt-get install gettext
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Environment Variable Replacement (override defaults)
        run: cat example.txt | envsubst