name: Test gha-env-variables

on:
  - push

jobs:
  test-gha-env-variables:
    runs-on: ubuntu-latest
    name: Test gha-env-variables
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Export Environment Variables
        uses: dmsi-io/gha-env-variables@feature/AW-597
        with:
          TLD: agility.dmsi.io
          GCP_PROJECT_ID: test-project-id

      - name: Print Environment Variable Replacement
        run: cat example.txt | envsubst

      - name: Export Environment Variables (override defaults)
        uses: dmsi-io/gha-env-variables@feature/AW-597
        with:
          TLD: agility.dmsi.io
          GCP_PROJECT_ID: test-project-id
          NAMESPACE: something/testing-OVERRIDE
          SERVICE_NAME: something/testing-override

      - name: Print Environment Variable Replacement (override defaults)
        run: cat example.txt | envsubst