name: Test gha-env-variables

on:
  - push
  - pull_request

jobs:
  test-gha-env-variables:
    runs-on: ubuntu-latest
    name: Test gha-env-variables
    steps:
      - name: Export Environment Variables
        id: export-vars
        uses: dmsi-io/gha-env-variables@feature/HOU-166
        with:
          TLD: ${{ secrets.TLD }}
          GCP_PROJECT_ID: test-project-id

      - name: Install envsubst
        run: |
          env | sort
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Environment Variable Replacement
        run: cat example.txt | envsubst

      - name: Print outputs
        run: |
          echo "OUTPUTS=$OUTPUTS"
        env:
          OUTPUTS: ${{ toJSON(steps.export-vars.outputs) }}

  test-gha-env-variables-defaults:
    runs-on: ubuntu-latest
    name: Test gha-env-variables (override defaults)
    steps:
      - name: Export Environment Variables (override defaults)
        uses: dmsi-io/gha-env-variables@feature/HOU-166
        with:
          TLD: agility.dmsi.io
          GCP_PROJECT_ID: test-project-id
          NAMESPACE: something/feature/---123-TEST-!@#$%-0000000000000000000000000000000000000000000000000012345---
          SERVICE_NAME: something/feature/---123-TEST-!@#$%-0000000000000000000000000000000000000000000000000012345---

      - name: Install envsubst
        run: |
          env | sort
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Environment Variable Replacement (override defaults)
        run: cat example.txt | envsubst
