name: Test gha-env-variables

on:
  push:
    branches:
      - '!main'

jobs:
  test-gha-env-variables:
    runs-on: ubuntu-latest
    name: Test gha-env-variables
    steps:
      - name: Export Environment Variables
        uses: dmsi-io/gha-env-variables@${{ github.ref_name }}