name: Test gha-env-variables

on:
  - push

jobs:
  test-gha-env-variables:
    runs-on: ubuntu-latest
    name: Test gha-env-variables
    steps:
      - name: Export Environment Variables
        id: export-vars
        uses: dmsi-io/gha-env-variables@feature/variable-outputs
        with:
          TLD: ${{ secrets.TLD }}
          GCP_PROJECT_ID: test-project-id

      - name: Install envsubst
        run: |
          env | sort
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Environment Variable Replacement
        run: cat example.txt | envsubst

      - name: Print outputs
        run: |
          echo "OUTPUTS=$OUTPUTS"
          echo "EXPORT_VARS=$EXPORT_VARS"
          echo "STEP_VARS=$STEP_VARS"
          echo "short_sha=${{ steps.export-vars.outputs.short_sha }}"
          echo "hostname=${{ steps.export-vars.outputs.hostname }}"
          echo "cert_name=${{ steps.export-vars.outputs.cert_name }}"
          echo "hard_coded=${{ steps.export-vars.outputs.hard_coded }}"
        env:
          OUTPUTS: ${{ toJSON(steps.export-vars.outputs) }}
          EXPORT_VARS: ${{ toJSON(steps.export-vars) }}
          STEP_VARS: ${{ toJSON(steps) }}

  test-gha-env-variables-defaults:
    runs-on: ubuntu-latest
    name: Test gha-env-variables (override defaults)
    steps:
      - name: Export Environment Variables (override defaults)
        uses: dmsi-io/gha-env-variables@main
        with:
          TLD: agility.dmsi.io
          GCP_PROJECT_ID: test-project-id
          NAMESPACE: something/feature/---123-TEST-!@#$%-0000000000000000000000000000000000000000000000000012345---
          SERVICE_NAME: something/feature/---123-TEST-!@#$%-0000000000000000000000000000000000000000000000000012345---

      - name: Install envsubst
        run: |
          env | sort
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Environment Variable Replacement (override defaults)
        run: cat example.txt | envsubst